[build]
  base    = "./"  # Points to repo root
  command = "echo 'No build needed'"  # For static sites
  publish = "./"  # Publish from root
  [[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
